// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import ru.stqa.pft.driver.webDriver;

//import static java.nio.file.Paths.get;


class testName {
  webDriver driver = new webDriver();
  //private Map<String, Object> vars;
    @Before
  public void setUp()  {
      //js = (JavascriptExecutor) driver;
    //vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
   // quit();
  }
  @Test
  public void name() {
    // Test name: name
    // Step # | name | target | value | comment
    // 1 | open | /addressbook/ |  | 
    get("http://localhost/addressbook/");
    // 2 | click | name=user |  | 
    //driver.findElement(By.name("user")).click();
    // 3 | type | name=user | admin | 
    //driver.findElement(By.name("user")).sendKeys("admin");
    // 4 | click | name=pass |  | 
    //driver.findElement(By.name("pass")).click();
    // 5 | type | name=pass | secret | 
   // driver.findElement(By.name("pass")).sendKeys("secret");
    // 6 | click | css=input:nth-child(7) |  | 
   // driver.findElement(By.cssSelector("input:nth-child(7)")).click();
    // 7 | click | linkText=ADD_NEW |  | 
   // driver.findElement(By.linkText("ADD_NEW")).click();
    // 8 | click | name=firstname |  | 
   // driver.findElement(By.name("firstname")).click();
    // 9 | type | name=firstname | test | 
    //driver.findElement(By.name("firstname")).sendKeys("test");
    // 10 | click | name=lastname |  | 
   // driver.findElement(By.name("lastname")).click();
    // 11 | type | name=lastname | test | 
    //driver.findElement(By.name("lastname")).sendKeys("test");
    // 12 | click | name=address |  | 
  //  driver.findElement(By.name("address")).click();
    // 13 | type | name=address | test22 | 
   // driver.findElement(By.name("address")).sendKeys("test22");
    // 14 | click | css=input:nth-child(87) |  | 
   // driver.findElement(By.cssSelector("input:nth-child(87)")).click();
    // 15 | click | id=top |  | 
   // driver.findElement(By.id("top")).click();
    // 16 | click | linkText=LOGOUT |  | 
    //driver.findElement(By.linkText("LOGOUT")).click();/
  }


}
